name: Coding standard

on: [ pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: db_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: json, openssl, pdo, redis
      - uses: actions/checkout@v4

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Phpstan
        run: |
          composer install --working-dir=tools/phpstan
          tools/phpstan/vendor/bin/phpstan

      - name: PHP Coding Standards Fixer
        run: |
          composer install --working-dir=tools/php-cs-fixer
          tools/php-cs-fixer/vendor/bin/php-cs-fixer fix -v --dry-run --stop-on-violation

      - name: "Setup environment"
        run: |
          .github/scripts/setup-environment.sh

      - name: PHPUnit
        run: |
          console doctrine:database:create --env=test
          console doctrine:schema:update --env=test --force
          bin/phpunit
